spring:

  application:
    name: WebApp

  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/admindb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  docker:
    compose:
      enabled: true